class Autogenerated {
  String? activity;
  String? type;
  int? participants;
  double? price;
  String? link;
  String? key;
  double? accessibility;

  Autogenerated(
      {this.activity,
        this.type,
        this.participants,
        this.price,
        this.link,
        this.key,
        this.accessibility});

  Autogenerated.fromJson(Map<String, dynamic> json) {

    activity = json['activity'].toString();
    type = json['type'].toString();
    participants = int.parse(json['participants'].toString());
    price = double.parse(json['price'].toString());
    link = json['link'].toString();
    key = json['key'].toString();
    accessibility = double.parse(json['accessibility'].toString());
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = <String, dynamic>{};
    data['activity'] = activity;
    data['type'] = type;
    data['participants'] = participants;
    data['price'] = price;
    data['link'] = link;
    data['key'] = key;
    data['accessibility'] = accessibility;
    return data;
  }
}