import 'dart:convert';

import 'package:api/Models/Boredapi.dart';
import 'package:flutter/material.dart';
import 'package:http/http.dart' as http;

class Boredapi extends StatefulWidget {
  const Boredapi({Key? key}) : super(key: key);

  @override
  State<Boredapi> createState() => _BoredapiState();
}

Future<Autogenerated>Boredapidetails()async{
  var det =  await http.get(Uri.parse("https://www.boredapi.com/api/activity"));
  return Autogenerated.fromJson(jsonDecode(det.body));

}


class _BoredapiState extends State<Boredapi> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Center(child: Text("Bored Api")),
        backgroundColor: Colors.blue,
      ),
      body: FutureBuilder<Autogenerated>(
        future: Boredapidetails(),
        builder: (context,snapshot){
          if (snapshot.hasData){
              return Column(
              children: [
                SizedBox(height: 100,),
              Padding(
                padding: const EdgeInsets.all(8.0),
                child: Center(child: Text(snapshot.data!.activity.toString())),
              ),
              Padding(
                padding: const EdgeInsets.all(8.0),
                child: Center(child: Text(snapshot.data!.accessibility.toString())),
              ),
                  Center(child: Text(snapshot.data!.type.toString())),
              ],
              );
              }
          else if (snapshot.hasError) {
            return Column(
            children :[
              const Icon(Icons.error_outline,
                  color: Colors.red,
                  size: 60,
    ),
              Padding(
                  padding: const EdgeInsets.only(top: 16),
                  child: Text('Error: ${snapshot.error}'),
    ),
    ]
    );
          }
          else {
            return Padding(
              padding: EdgeInsets.only(top: 48.0,left: 150),
              child: Column(
                  children :[
                    SizedBox(
                              width: 60,
                      height: 60,
                      child: CircularProgressIndicator(),
    ),
                    Padding(
                    padding: EdgeInsets.only(top: 16),
                    child: Text('Awaiting result...'),
                    ),
    ]
              ),
            );
          }
          }
      ) ,
    );
  }
  void initState(){
    super.initState();
    Boredapidetails();
  }
}
